version: "1.0"
stages:
  - "prep"
  - "sync"
  - "test"

steps:

  notify_slack_start:
    title: Pre-sync Slack notification
    stage: prep
    type: slack-notifier
    arguments:
      SLACK_HOOK_URL: '${{SLACK_WEBHOOK_URL}}'
      SLACK_TEXT: 'Starting sync of Argo CD app: ${{ARGOCD_APP_NAME}}'
      # SLACK_ATTACHMENTS: '${{SLACK_ATTACHMENTS}}'

  sync_and_wait:
    title: Sync ArgoCD app and wait
    stage: sync
    type: argocd-sync
    arguments:
      context: '${{ARGOCD_AGENT}}'  # Name of the agent in Codefresh, Integrations->GitOps
      app_name: '${{ARGOCD_APP_NAME}}'
      wait_healthy: true
      debug: true
      additional_flags:
        - '--grpc-web'  # Seems to always be needed, regardless of Argo CD using LB svc or Ingress
        # - --loglevel debug. # Probably best to comment this out when not debugging

  notify_slack_finished:
    title: Post-sync Slack notification
    stage: test
    type: slack-notifier
    arguments:
      SLACK_HOOK_URL: '${{SLACK_WEBHOOK_URL}}'
      SLACK_TEXT: 'Finished sync of Argo CD app: ${{ARGOCD_APP_NAME}}'
      # SLACK_ATTACHMENTS: '${{SLACK_ATTACHMENTS}}'
