# Default values for Flaskr deployments
replicaCount: 1
image:
  pullPolicy: IfNotPresent
  repository: 336151728602.dkr.ecr.us-east-1.amazonaws.com/flaskr
  tag: SAAS-8431-cd261d9
service:
  name: flaskr
  type: LoadBalancer
  externalPort: 80
  internalPort: 5000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
